### ISSUE TITLE
Doesn't Generate in MC1.10

### ISSUE THREAD

**Issue by kurisubrooks** [Barteks2x/173generator#12]
Unfortunately, after compiling 173generator from source, 173generator does not work in Minecraft 1.10. Would this be something you'd be willing to work on?

Using MCPaper build 881 (Spigot but _faster_)

```
[22:46:49 INFO]: [173generator] Loading 173generator v${describe}
[22:46:49 WARN]: [173generator] Unknown server version: git-Paper-881 (MC: 1.10.2), plugin may work incorrectly or crash!
[22:46:49 INFO]: [173generator] Enabling 173generator v${describe}
```

```
>plugins
[22:47:19 INFO]: Plugins (1): 173generator
```

There is no crash log or any errors.

**Comment by Barteks2x** [comment]
I will look into that. But first try to test it with all other plugins removed and with Spigot itself. If spigot doesn't work - try plain CraftBukkit (spigot build tools generates craftbukkit jar too)

**Comment by kurisubrooks** [comment]
They're building now. Will get back to you.

**Comment by kurisubrooks** [comment]
Doesn't work on Spigot, testing CraftBukkit now

**Comment by kurisubrooks** [comment]
I'll give your old 1.8 build a try (from dev.bukkit), see is I have any luck with that.

**Comment by Barteks2x** [comment]
That's strange. I was sure it works. The only way I'm sure won't work is when you use /reload command. I will try myself.

**Comment by kurisubrooks** [comment]
The friend who compiled it for me thinks there might have been a problem compiling, he's going through the 42 warnings he received now.

**Comment by Barteks2x** [comment]
Try to compile without running unit tests. These require cloning the submodule too.

**Comment by kurisubrooks** [comment]
The 1.8 version from Dev Bukkit works for me under PaperMC. My friend also just recompiled and it's now working for him too. He forgot to add craftbukkit.jar manually..

He would also like me to point out that protocollib is imported but unused. 
Thanks for your help, sorry to bug you with our confusion.
I'll close this as it seems it was our fault.
