### ISSUE TITLE
Saplings don't grow

### ISSUE THREAD

**Issue by kurisubrooks** [Barteks2x/173generator#13]
In the latest build, saplings don't appear to grow, not normally nor with bone meal.
This causes quite a problem for both survival and creative players using this plugin.

**Comment by Barteks2x** [comment]
Are you sure there is enough space for them to grow? Are there any errors in console?

If it's neighter, then something bust have changed in bukkit.

**Comment by kurisubrooks** [comment]
Yes, there's plenty of room. I even tried on a block in the middle of the sky. Even after 2 stacks of bonemeal there was no growth at all.

It was not working in the 1.8 build also, so i'm guessing it's definitely on Bukkit's end.

My friend managed to get them working again with a modified build he made from your repo, he told me to tell you 

> in the place where you check if it's LEAVES or AIR, add an OR clause for SAPLING

He would submit a PR, but he couldn't get Spruce saplings to work, and his repo is too dirty

**Comment by kurisubrooks** [comment]
cc: @justin97530

**Comment by Barteks2x** [comment]
That was something I didn't expect. Beta version just checked if the block is transparent but that also makes trees replace glass and a few other transparent blocks which is not good and I tried to avoid it. I guess I tried too hard.

**Comment by kurisubrooks** [comment]
👏  Your efforts are greatly appreciated regardless of bugs

**Comment by Barteks2x** [comment]
I will debug and fix it tomorrow.

**Comment by kurisubrooks** [comment]
Any progress? 😄

**Comment by Barteks2x** [comment]
Still working on it, I has to change quite a bit of code to get trees to generate the right way.

I also found something interesting: beta 1.7.3 doesn't need to check for sapling in tree generation code because when attempting to generate tree, the sapling is temporarily removed: https://github.com/Bukkit/mc-dev/blob/1a792ed860ebe2c6d4c40c52f3bc7b9e0789ca23/net/minecraft/server/BlockSapling.java#L37-L53

**Comment by kurisubrooks** [comment]
Huh. Interesting logic on Bukkit's behalf. Glad to see you're working on
the bug fix though 🙂

**Comment by Barteks2x** [comment]
It should work now, also the bukkit API to generate trees is now used correctly (or at least I hope so).

**Comment by kurisubrooks** [comment]
I'll be able to test in about an hour. Thanks so much!
