### ISSUE TITLE
flying snow

### ISSUE THREAD

**Issue by BloodEko** [Barteks2x/173generator#16]
Hey.
Small snow blocks aren't played above grass, they are also placed above other snow blocks, so 50% of all snowblocks are flying.
Screenshot: http://www.bilder-upload.eu/show.php?file=80ba0d-1501828456.png

**Comment by Barteks2x** [comment]
This is a bug in your craftbukkit/spigot implementation running population twice. Bug them about it.

**Comment by BloodEko** [comment]
Do you maybe have some more informations where the error could be located ?
