### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by Charadon** [Barteks2x/173generator#23]
I'm having issues compiling this (since there's no pre-compiled version for 1.12.2, I have no compile it) and i'm getting this error when compiling

[error.log](https://github.com/Barteks2x/173generator/files/2074789/error.log)

It seems to be a repository issue, but I could be wrong.

**Comment by Barteks2x** [comment]
ProtocolLib seems to be gone. I'm no longer working on this plugin so I won't fix it. You should be able to remove this dependency and comment out the relevant code (it's used only to re-send biome information after biome regeneration).
